#
# Network IV Setup File
#

#unset NW4_PUSH_BUTTONS
#unset NW4_DISPLAY_MODE_BY_ROW

export NW4_SOUND_DEVICE=/dev/ttyACM0
export NW4_DISPLAY_DEVICE=/dev/ttyACM1
export NW4_DISPLAY_MODE_BY_ROW=1
export NW4_READ_BUTTONS=1


#export NW4_PUSH_BUTTONS=17


#export NW4_DEBUG=1
#export NW4_SOUND_DEBUG=1
#export NW4_DISPLAY_DEBUG=1
#export NW4_INPUT_DEBUG=1

echo SOUND: $NW4_SOUND_DEVICE
echo DISPLAY: $NW4_DISPLAY_DEVICE
echo BUTTONS: $NW4_READ_BUTTONS
echo DISPLAY_MODE: $NW4_DISPLAY_MODE_BY_ROW
